=== anniemarttinez-gif/Tulipan-Clothes/LENGUAJE DE MARCAS/esquema.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

    <xs:element name="catalogo">
        <xs:complexType>
            <xs:sequence>
                <!-- Cardinalidad -->
                <xs:element name="producto" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <!-- Tipo de dato -->
                            <xs:element name="nombre" type="xs:string" />
                            <!-- Restricción-->
                            <xs:element name="precio">
                                <xs:simpleType>
                                    <xs:restriction base="xs:decimal">
                                        <xs:minInclusive value="0" />
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>

                            <!-- Tipo de dato-->
                            <xs:element name="stock" type="xs:integer" />

                            <!-- Tipo de dato-->
                            <xs:element name="talla" type="xs:string" />
                            <xs:element name="color" type="xs:string" />
                            <xs:element name="categoria" type="xs:string" />
                        </xs:sequence>

                        <!-- Atributo-->
                        <xs:attribute name="id" type="xs:integer" use="required" />
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

</xs:schema>

=== anniemarttinez-gif/Tulipan-Clothes/LENGUAJE DE MARCAS/productos.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- Catálogo-->
<catalogo xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="esquema.xsd">
    <producto id="1">
        <nombre>Abaya Open-Front Lino</nombre>
        <precio>49.99</precio>
        <stock>20</stock>
        <talla>Talla Unica</talla>
        <color>Arena</color>
        <categoria>Abayas y Sobretodos</categoria>
    </producto>

    <producto id="2">
        <nombre>Vestido Nour de Rezo</nombre>
        <precio>35.00</precio>
        <stock>15</stock>
        <talla>S-M</talla>
        <color>Azul Profundo</color>
        <categoria>Prendas de Rezo</categoria>
    </producto>

    <producto id="3">
        <nombre>Mangas Contemporaneas</nombre>
        <precio>9.00</precio>
        <stock>100</stock>
        <talla>Talla Unica</talla>
        <color>Negro</color>
        <categoria>Complementos</categoria>
    </producto>
</catalogo>
